### ISSUE TITLE
"missing tag prefix" under Moodle 2.5.3

### ISSUE THREAD

**Issue by ejohnlove** [middlebury/moodle-mod_adaptivequiz#19] opened 2014-05-22 19:45 UTC
This plugin (although for version 2.3) installs under 2.5.3. However, I get athis error when trying to start an attempt on a quiz:

Missing tag prefix

More information about this error

Debug info: 
Error code: missingtagprefix
Stack trace:
line 476 of /lib/setuplib.php: moodle_exception thrown
line 412 of /mod/adaptivequiz/fetchquestion.class.php: call to print_error()
line 238 of /mod/adaptivequiz/fetchquestion.class.php: call to fetchquestion->retrieve_tags_with_question_count()
line 266 of /mod/adaptivequiz/fetchquestion.class.php: call to fetchquestion->initalize_tags_with_quest_count()
line 358 of /mod/adaptivequiz/adaptiveattempt.class.php: call to fetchquestion->fetch_questions()
line 337 of /mod/adaptivequiz/adaptiveattempt.class.php: call to adaptiveattempt->get_question_ready()
line 209 of /mod/adaptivequiz/attempt.php: call to adaptiveattempt->start_attempt()

**Comment by adamfranco** [comment] 2014-06-03 17:23
Closing this as a duplicate of #20 .

**Closed as completed by adamfranco** 2014-06-03 17:23 UTC
